### ISSUE TITLE
Checkers: King forced to make illegal move

### ISSUE THREAD

**Issue by jimu** [freeboardgames/FreeBoardGames.org#629] opened 2020-10-01 21:47 UTC
When playing against the AI, the players Kinged checker is forced to make the illegal move as shown in this screenshot:

![Illegal checkers move](https://i.imgur.com/nazecUd.png)

The player is allowed to make the illegal move as shown here:

![Illegal move allowed](https://i.imgur.com/DskJLYQ.png)

Notice that the white piece in E4 appears to have been taken

**Comment by flamecoals** [comment] 2020-10-02 14:41
Hi, thanks for reporting the bug! Closing because this is a duplicate of #604. 

I believe this might be a misunderstanding about checkers rules, as they vary by region.  I think we should change the rule to be based on the most common US/International played rules, which would make this move illegal. However, I also believe we need to open the possibility of rule variations within the game.

**Closed by flamecoals** 2020-10-02 14:41 UTC
