### ISSUE TITLE
Reload button in top right corner for online game mode, especially for mobile phones.

### ISSUE THREAD

**Issue by gk-patel** [freeboardgames/FreeBoardGames.org#649] opened 2020-11-03 21:06 UTC
We have a nice adroid app and also the game can be added as a web app on iPhone. 
This is what happens sometimes (when connection is poor, e.g. when travelling) 
Maybe due to network related problem, packets would be getting dropped (just an assumption). 
I see that "waiting for opponent....", but on the contrary the other person is waiting for me. 
And when the other person gets bored, he write a text message :( 
For this reason, I actually avoid using the app and prefer to use the browser :( 
This also happens in the browser, but you can reload.

**Comment by flamecoals** [comment] 2020-11-06 06:02
Duplicate of #650

**Closed by flamecoals** 2020-11-06 06:02 UTC
