### ISSUE TITLE
Last Player Leaving Room leaves Lobby in Inconsistent State

### ISSUE THREAD

**Issue by cwatsonc** [freeboardgames/FreeBoardGames.org#641] opened 2020-10-23 19:10 UTC
Replication Steps:

Client A connects and creates a public room for a game (cardtable shown).  The game creator is waiting for an opponent and shows 1/2 from lobby.

Client B connects to Lobby and sees the waiting game room 1/2

Client A cancels from room and now sees waiting game room 1/2

Client B sees 1/2 in room (if joining, they will see no opponent in room).

Client A refreshes the lobby; room is no longer present.

Client B will see room indefinitely unless refreshed.

<img width="1422" alt="Screen Shot 2020-10-23 at 12 02 42 PM" src="https://user-images.githubusercontent.com/23615127/97044187-9190e780-1528-11eb-9497-f1f7db0f23e1.png">

**Comment by cwatsonc** [comment] 2020-10-23 19:20
Additional Information:  If in above scenario Client B joins the room then leaves, the game is cleared from the lobby.  Seems to be a problem with the end game state calculation.  Discovered this behavior on Tic-Tac-Toe.

**Comment by flamecoals** [comment] 2020-11-13 07:26
I think this is related to issues with the pub/sub notifications not working for you. Are you still running into this issues?

**Comment by flamecoals** [comment] 2020-11-28 03:33
Im closing this as I cant reproduce since we fixed the pub/sub issues

**Closed by flamecoals** 2020-11-28 03:33 UTC
